# https://docs.docker.com/compose/compose-file/
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
      target: build
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      db_migration:
        condition: service_started
    environment:
      - DB_HOST=db
    tty: true
    stdin_open: true
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cr-scraper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  db_migration:
    build:
      context: .
      target: db_migration
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
# ===============================
# tests, formatting and linting
# ===============================
  tests:
    build:
      context: .
      target: tests_lint_format
    volumes:
      - ./test_results:/app/test_results
    entrypoint: ./entrypoint.tests.sh
  format:
    build:
      context: .
      target: tests_lint_format
    entrypoint: ./entrypoint.format.sh
  lint:
    build:
      context: .
      target: tests_lint_format
    entrypoint: ./entrypoint.lint.sh
volumes:
  db-data:
    driver: local
