"""Groceries and grocery_lists tables

Revision ID: e9aedd17ed96
Revises:
Create Date: 2023-11-11 18:47:18.128079

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9aedd17ed96"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grocery_lists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "groceries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column(
            "unit",
            sa.Enum("KG", "G", "MG", "L", "ML", name="unit", create_constraint=True),
            nullable=True,
        ),
        sa.Column("list_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["grocery_lists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("groceries")
    op.drop_table("grocery_lists")
    # ### end Alembic commands ###
