"""Converting from enum to string

Revision ID: 75ccfb61d19b
Revises: e9aedd17ed96
Create Date: 2023-11-11 23:43:25.600138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "75ccfb61d19b"
down_revision: Union[str, None] = "e9aedd17ed96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "groceries",
        "unit",
        existing_type=postgresql.ENUM("KG", "G", "MG", "L", "ML", name="unit"),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "groceries",
        "unit",
        existing_type=sa.String(),
        type_=postgresql.ENUM("KG", "G", "MG", "L", "ML", name="unit"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
